sub-font="Arial"
screenshot-format="png"
screenshot-template="%F-%P"
screenshot-directory="/home/guts/Pictures/"
ao=pipewire
hwdec=auto-safe
ytdl-raw-options=sub-langs="en.*,.*",write-subs=,write-auto-subs=
# default to en subtitiles
slang=en,eng,en-US
