[hotkey]
enabled = false

[whisper]
model = "large-v3-turbo"   # tiny, base, small, medium, large-v3, large-v3-turbo
language = "en"     # Or "auto" for detection, or language code (es, fr, de, etc.)
translate = false   # Translate non-English speech to English

[output]
mode = "type"       # "type", "clipboard", or "paste"
fallback_to_clipboard = true

[output.notification]
on_recording_start = true   # Notify when PTT activates
on_recording_stop = true    # Notify when transcribing
on_transcription = true     # Show transcribed text

[audio]
# device = "clean-mic-line-out"  # Or specific device from `pactl list sources short`
device = "pipewire" # after running `pactl set-default-source clean-mic-line-out` once, bug: https://github.com/peteonrails/voxtype/issues/564 (don't forget to daemon reload)
sample_rate = 16000
max_duration_secs = 120
