wireplumber.components = [
  {
    # not sure how to avoid giving the full path here, need to experiment some options
    name = /home/guts/.config/wireplumber/scripts/auto-link-usb-mic.lua 
    type = script/lua
    provides = custom.auto-link-usb-mic
  }
]

wireplumber.profiles = {
  main = {
    custom.auto-link-usb-mic = required
  }
}

